name = Contact
description = Contact page layout
template = contact-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/contact/contact.layout.css
stylesheets[all][] = css/layouts/contact/contact.layout.no-query.css